# Assignment # 2 (NumPy)
## Roll No: PIAIC108704
## Name: Muhammad Idrees

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [4]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
matrix = arr.reshape(2,-1)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
arr1 = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2 = np.ones(10, dtype="int64").reshape(2,-1)
print(arr1)
print(arr2)
print("========== OUTPUT ==========")
v_stack_arr = np.vstack((arr1,arr2))
print(v_stack_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
========== OUTPUT ==========
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
arr1 = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2 = np.ones(10, dtype="int64").reshape(2,-1)
print(arr1)
print(arr2)
print("========== OUTPUT ==========")
v_stack_arr = np.hstack((arr1,arr2))
print(v_stack_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
========== OUTPUT ==========
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [10]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
print(arr)
print("========== OUTPUT ==========")
new_arr = arr.flatten()
print(new_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
========== OUTPUT ==========
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [11]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
print(arr)
print("========== OUTPUT ==========")
new_arr = arr.flatten()
print(new_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
========== OUTPUT ==========
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [12]:
arr = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
print(arr)
print("========== OUTPUT ==========")
new_arr = arr.reshape(5,3)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
========== OUTPUT ==========
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [19]:
arr = np.arange(25).reshape(5,5)
print(arr)
sqrt_arr = np.sqrt(arr)
print("========================= OUTPUT =========================")
print(sqrt_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
========================= OUTPUT =========================
[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]
 [3.87298335 4.         4.12310563 4.24264069 4.35889894]
 [4.47213595 4.58257569 4.69041576 4.79583152 4.89897949]]


## Question:8

### Create 5x6 an array and find the mean?

In [21]:
arr = np.arange(30).reshape(5,6)
print(arr)
mean_arr = np.mean(arr)
print("========================= OUTPUT =========================")
print(mean_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
========================= OUTPUT =========================
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [22]:
arr = np.arange(30).reshape(5,6)
print(arr)
std_arr = np.std(arr)
print("========================= OUTPUT =========================")
print(std_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
========================= OUTPUT =========================
8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [23]:
arr = np.arange(30).reshape(5,6)
print(arr)
med_arr = np.median(arr)
print("========================= OUTPUT =========================")
print(med_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
========================= OUTPUT =========================
14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [24]:
arr = np.arange(30).reshape(5,6)
print(arr)
T_arr = arr.T
print("========================= OUTPUT =========================")
print(T_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
========================= OUTPUT =========================
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [28]:
arr = np.arange(16).reshape(4,4)
print(arr)
diag_elements = np.diag(arr)
print("========================= OUTPUT =========================")
print(f"Sum of diagonal element {diag_elements} is {np.sum(diag_elements)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
========================= OUTPUT =========================
Sum of diagonal element [ 0  5 10 15] is 30


## Question:13

### Find the determinant of the previous array in Q12?

In [38]:
arr = np.arange(16).reshape(4,4)
print(arr)
det_arr = np.linalg.det(arr)
print("========================= OUTPUT =========================")
print(f"Determinent of Array element is {det_arr}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
========================= OUTPUT =========================
Determinent of Array element is 0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [40]:
arr = np.arange(16)
print(arr)
percentile_5th = np.percentile(arr,5)
percentile_95th = np.percentile(arr,95)
print("========================= OUTPUT =========================")
print(f"5th Percentile is {percentile_5th}\n95th Percentile is {percentile_95th}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
========================= OUTPUT =========================
5th Percentile is 0.75
95th Percentile is 14.25


## Question:15

### How to find if a given array has any null values?

In [42]:
arr = np.array([1,2,3,0,8,7,0,5,0,6,0,7])
arr == 0

array([False, False, False,  True, False, False,  True, False,  True,
       False,  True, False])

In [43]:
arr = np.array([1,2,3,0,8,7,0,5,0,6,0,7])
arr[arr == 0]

array([0, 0, 0, 0])